### ISSUE TITLE
[Feature Request]: Waterfall plot / stacked plot

### ISSUE THREAD

**Issue by thorstenmaly** [DNPLab/DNPLab#10]
We should be able to display pseudo-2D spectra (e.g. NMR spectrum vs. power) in a waterfall plot or stacked plot.

For example see this:
http://chem.ch.huji.ac.il/nmr/techniques/other/diff/diff_files/stackplot.gif

**Comment by thorstenmaly** [comment]
Can we add keywords for x, y offset and also fill (true=default / false)?

**Comment by ylin00** [comment]
@thorstenmaly Has this issue been closed by #33 ?
