### ISSUE TITLE
Make behavior of functions similar

### ISSUE THREAD

**Issue by thorstenmaly** [DNPLab/DNPLab#100]
Some functions (e.g. in the dnpNMR module) modify the processing buffer, others (e.g. calculate_enhancements) create a new key in the workspace.
We should come up with a consistent way how to handle that. Some functions for example in the NMR processing module create temporary data, which is probably not important to store. Others like integrate or enhancement create data that is worth keeping. However, the integrate does not do that currently.

We should make this very clear in the documentation if a function modifies the proc buffer or not.

**Comment by thcasey3** [comment]
I think this revives our earlier discussions about what is and isn't a processing step, or what is just a change in the data and what is some measure of a characteristic of the data. Personally, I think the any step that reduces the data to a single or few attributes of the data should be added as an attribute of the object and not considered a processing step. Anything that transforms the data to another domain or adjusts the data but retains its nature should be a processing step. For example: the integral is a characteristic of the spectrum, it is a fundamentally different piece of information than the spectrum itself, it has no structure or other information content it is just a single measure. Creating this should not replace the data in the object. Same with performing a fit, this extracts piece(s) of information from the data but the fit is fundamentally different than the data and is by nature its own separate piece of information. On the other hand, a baseline correction or offset removal are just alterations to the data but the data retain their nature. Even a Fourier transform, the data are transformed to the frequency representation but they are still of the same general nature, full of more than just one measure or piece of information, this is a processing step. If we can draw a clear line like this between what is and isn't a processing step we can give each function one of two possible behaviors, in-place operation or new item added to object.

**Comment by thorstenmaly** [comment]
I like that definition. Maybe distinguish between processing and analyzing?
processing replaces the data in the object, analyzing adds a new key to the workspace (similarly what you're doing in the enhancement function)?

**Comment by thcasey3** [comment]
That would be my preference. So, for example,

Category 1 - processing, in-place operation
1. align
2. autophase (add phase measure as attribute)
3. fourier_transform
4. inverse_fourier_transform
5. left_shift
6. window (add window as attribute)
7. remove_offset
8. phase_cycle

Category 2 - analysis, new key
1. integrate
2. calculate_enhancement
3. dnpFit module (new key has fit itself and fit parameters as attributes)
4. signal_to_noise (or maybe this is just an attribute added to proc?)
5. dnpHydration module

**Comment by thcasey3** [comment]
closed by #107
