### ISSUE TITLE
Calculate_enhancements should just do that

### ISSUE THREAD

**Issue by thorstenmaly** [DNPLab/DNPLab#103]
Currently the calculate_enhancement function is also performing an integration of the data. However, this will lead to duplicate functions in DNPLab. This issue is also related (somehow) to [#100 ](https://github.com/DNPLab/DNPLab/issues/100)

I would suggest the following:

- To calculate enhancements the user should first perform an integration. The user should be able to define multiple integration windows (given by center and width).
- Results of the integration are stored in a separate workspace key e.g. "Integrals"
- Calculate_enhancements will use these integrals to perform calculation and return results in workspace key "Enhancements"
- If the user just invokes calculate_enhancements without a integration then the calculate_enhancement function should call the integrate function, perform an integration over the entire spectral range, store the data in the new workspace key ("integrals"), then calculate the enhancement and return the results in workspace key "Enhancements"

**Comment by thcasey3** [comment]
@tkeller12 im working on this

**Comment by thcasey3** [comment]
closed by Pr #106
