### ISSUE TITLE
Two successive dnpResults.plot() calls plot on same plot

### ISSUE THREAD

**Issue by thcasey3** [DNPLab/DNPLab#104]
Users should be allowed to raise two successive plots, rather than plot everything on the same plot. For example, these should work and raise two plots:
```
plot1 = dnp.dnpResults.plot(ws["raw"])
plot1.show()
dnp.dnpTools.integrate(ws)
plot2 = dnp.dnpResults.plot(ws["proc"])
plot2.show()
```
The dnpResults.plot method should return the plot object to be interacted with.

OR this should raise two plots,
```
dnp.dnpResults.plot(ws["raw"])
dnp.dnpTools.integrate(ws)
dnp.dnpResults.plot(ws["proc"])
```
while this plots them together,
```
dnp.dnpResults.plot(ws["raw"], ws["proc"])
```

**Comment by tkeller12** [comment]
You should call the function "figure" to create a new figure. For example

```
dnp.plot(data1)
dnp.figure()
dnp.plot(data2)
```

**Comment by thcasey3** [comment]
@tkeller12 ok, I agree with that
