### ISSUE TITLE
dnpResults.plot should default assume real to avoid 'ComplexWarning'

### ISSUE THREAD

**Issue by thcasey3** [DNPLab/DNPLab#105]
Default plot behavior for:
```
dnpResult.plot(object)
```
should be `object.real` to avoid:
```
ComplexWarning: Casting complex values to real discards the imaginary part
```
Users can see imaginary with:
```
dnpResult.plot(object.imag)
```
OR both with:
```
dnpResult.plot(object.real, object.imag)
```

**Comment by tkeller12** [comment]
I don't think this should be the desired behavior. If the user wants to specifically plot either real or imaginary data, they should specify this explicitly when they use the plot function. The ComplexWarning you are getting has to do with matplotlib. I would like for the numpy and matplotlib functions to behave exactly as they would if the user inputs a ndarray object.

**Comment by thorstenmaly** [comment]
I'm with Tom on this one. In NMR, there is rarely a situation in which you have to look at the imag spectrum.  I do get your point about functions behaving the same as from matplotlib, but then you can use that one.

**Comment by thcasey3** [comment]
my opinion is that DNPLab behavior should be specific to what the majority of DNP/NMR users do since it is a DNP/NMR specific package. if it is **most common** to omit the imaginary in a plot, and we default to this, it should not be a warning
