### ISSUE TITLE
Error in window function

### ISSUE THREAD

**Issue by thorstenmaly** [DNPLab/DNPLab#109]
Saving h5 data only works if I uncomment line 848 of the window function.
Tim should fix this one, he knows what the problem is.

RuntimeError: Unable to create attribute (object header message is too large)

**Comment by thcasey3** [comment]
I can't reproduce this error for any data that is windowed, @thorstenmaly @tkeller12 can you post minimal code to reproduce it with one of the test data sets?

**Comment by thcasey3** [comment]
Ok I get the error with 1D Bruker data, not with 2D

**Comment by thcasey3** [comment]
@tkeller12 @thorstenmaly there is also a dims inconsistent warning for loading after integration over multiple regions. I will work on updating h5.py in general
