### ISSUE TITLE
[Feature Request]: Left shift of data

### ISSUE THREAD

**Issue by thorstenmaly** [DNPLab/DNPLab#11]
Implement function to left shift data for example to discard the first few points. Do not add to the end, this can be dealt later with by the fourier transformation.

This is helpful when using an echo sequence for detection so the user does not have to adjust the acquisition delay accurately but can do this later when post-processing the data.

**Comment by thorstenmaly** [comment]
Actually, it would be good to shift in both directions.

leftShift(data,npts) and npts is negative to shift left, positive to shift right?

This function can come in handy later when we want to implement linear prediction.

**Comment by ylin00** [comment]
Do you mean by the following example, where `x` is defined as a numeric vector, `npts` a signed integer, and the result `y` a vector with padding zeros?   
```
x = [0, 1, 2, 3, 4, 5, 6]

# Right shift
y = shift(x, npts=2)
assert y == [0, 0, 0, 1, 2, 3, 4]

# Left shift
y = shift(x, npts=-2)
assert y == [2, 3, 4, 5, 6, 0, 0]
```

**Comment by thcasey3** [comment]
added in pull request #80
