### ISSUE TITLE
Trouble calculating DNP enhancement between two NMR spectra. 

### ISSUE THREAD

**Issue by thomasrwebber** [DNPLab/DNPLab#134]
**What happened**: Received an error when writing my own dnpLab script for plotting NMR data and calculating DNP enhancement. I am able to plot NMR spectra, following the example scripts: "01 - DNPLab Basics (TopSpin Data)" and "02 - DNPLab Basics (Kea Data)", but I can't calculate an enhancement from two spectra (trying to follow examples "04 - Create a 2D dnpdata Object from Individual Spectra" and "05 - Calculate DNP Enhancements (I)".

**What you expected to happen**: I expected to create a 2D dnpdata object from 2 individual spectra (one with power off, one with power on), then calculate the enhancement of the spectra with the power on. 

**Minimal Complete Verifiable Example**:

```python
########## OFF Signal (P = 0 W) ##########
data_off = dnp.dnpImport.load("C:/Users/thoma/Documents/UCSB Research/Lab Data/ODNP/20210601_TEMPOL_1mM_HanLab/1",data_type="topspin")
ws = dnp.create_workspace()    # Create workspace (this is where all data is stored for this experiment)
ws.add("rawOff", data_off)     # Add imported data to the workspace as "rawOff" key
ws.copy("rawOff", "proc")      # Copy the raw data to the processed data before processing it
dnp.dnpNMR.remove_offset(ws)                            # Remove DC offset from proc buffer
dnp.dnpNMR.window(ws, linewidth=20)                     # Apply a 15 Hz linewidth to proc buffer
dnp.dnpNMR.fourier_transform(ws, zero_fill_factor=2)    # Fourier transform the proc buffer
dnp.dnpNMR.autophase(ws)
ws.copy("proc", "offSignal")      # Copy the newly processed buffer to the buffer called "offSignal"

########## ON Signal (P = 0.1 W, or 20 dBm) ##########
data_on = dnp.dnpImport.load("C:/Users/thoma/Documents/UCSB Research/Lab Data/ODNP/20210601_TEMPOL_1mM_HanLab/2",data_type="topspin")
ws.add("rawOn", data_on)
ws.copy("rawOn")
dnp.dnpNMR.remove_offset(ws)
dnp.dnpNMR.window(ws, linewidth=20)
dnp.dnpNMR.fourier_transform(ws, zero_fill_factor=2)
dnp.dnpNMR.autophase(ws)
ws.copy("proc", "onSignal")

########## Plot Spectra ##########
dnp.dnpResults.figure()
dnp.dnpResults.plot(ws["offSignal"].real, label = "Off Signal")
dnp.dnpResults.plot(ws["onSignal"].real, label = "On Signal")
dnp.dnpResults.xlim([30, -30])
dnp.dnpResults.plt.xlabel("Chemical Shift [ppm]")
dnp.dnpResults.plt.ylabel("Signal Amplitude [a.u.]")
dnp.dnpResults.plt.title("DNP On/Off Signal, 1 mM TEMPO in Water")
dnp.dnpResults.plt.legend()
dnp.dnpResults.plt.grid(True)
dnp.dnpResults.show()

######### Calculate Enhancement ###########
filenames = [
    "C:/Users/thoma/Documents/UCSB Research/Lab Data/ODNP/20210601_TEMPOL_1mM_HanLab/1",
    "C:/Users/thoma/Documents/UCSB Research/Lab Data/ODNP/20210601_TEMPOL_1mM_HanLab/2",]
powers = np.array([0,20])   # Power in dBm
data_enh = dnp.dnpImport.load(filenames, dim = "Power", coord = powers)   # This is the line that gives me an error: "TypeError: expected str, bytes or os.PathLike object, not list"
ws1 = dnp.create_workspace()
ws1.add("raw", data_enh)
ws1.copy("raw", "proc")
dnp.dnpNMR.calculate_enhancement(ws1)
```

**Anything else we need to know?**: How do I calculate the enhancement between my two spectra? The dnpNMR.calculate_enhancement function doesn't work unless I pass in a 2D dnplab data object, which I have trouble creating. Thanks for helping! I am not a python expert, and this is my first Issue Report on GitHub, so I apologize if this is a basic issue!

**Environment**:

<details><summary>Output of <tt>pip show dnplab</tt></summary>

Name: dnplab
Version: 1.0.3
Summary: DNPLab - Bringing the Power of Python to DNP-NMR Spectroscopy
Home-page: http://dnpLab.net
Author: DNPLab Team
Author-email: None
License: MIT
Location: c:\users\thoma\anaconda3\lib\site-packages
Requires: h5py, matplotlib, PyQt5, scipy, numpy
Required-by:

</details>

**Comment by thomasrwebber** [comment]
Here are my two NMR spectra, if it helps! 
[2.zip](https://github.com/DNPLab/DNPLab/files/6666582/2.zip)
[1.zip](https://github.com/DNPLab/DNPLab/files/6666583/1.zip)

**Comment by thcasey3** [comment]
Hi @thomasrwebber, it looks like you forgot to process and integrate first. You can either do the integration within calculate_enhancement or integrate first.  It is much easier to integrate first so I'll show you that way:
```
######### Calculate Enhancement ###########
filenames = [
    "C:/Users/thoma/Documents/UCSB Research/Lab Data/ODNP/20210601_TEMPOL_1mM_HanLab/1",
    "C:/Users/thoma/Documents/UCSB Research/Lab Data/ODNP/20210601_TEMPOL_1mM_HanLab/2",]
powers = np.array([0,20])   # Power in dBm
data_enh = dnp.dnpImport.load(filenames, dim = "Power", coord = powers)
ws1 = dnp.create_workspace("raw", data_enh)
ws1.copy("raw", "proc")
dnp.dnpNMR.remove_offset(ws1)
dnp.dnpNMR.window(ws1, linewidth=20)
dnp.dnpNMR.fourier_transform(ws1, zero_fill_factor=2)
dnp.dnpNMR.autophase(ws1)
dnp.dnpTools.integrate(ws1, integrate_center=0, integrate_width=60)
dnp.dnpNMR.calculate_enhancement(ws1, dim="Power")
print("Enhancements: " + str(ws1["enhancements"].values))
```
Adjust the integrate center and widths as necessary, for this example I set it equal to the span of the plot you make. Also, notice that since you named your dimension "Power" you need to specify this in the calculate_enhancement call.

**Comment by thomasrwebber** [comment]
The issue, it turned out, was an out-of-date version of dnplab. Thanks Tom for the help!

**Comment by thcasey3** [comment]
No problem! Thanks for using the issue tracker, let us know anytime you have issues.
