### ISSUE TITLE
[Installation] An invalid requirement: 'sip >=5.0.1 <6

### ISSUE THREAD

**Issue by ehuang94** [DNPLab/DNPLab#135]
Collecting dnplab
  Using cached dnplab-1.0.4-py3-none-any.whl (100 kB)
Requirement already satisfied: matplotlib>=3.3 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from dnplab) (3.4.2)
Requirement already satisfied: numpy>=1.19 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from dnplab) (1.20.1)
Requirement already satisfied: h5py>=2.10 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from dnplab) (3.2.1)
Requirement already satisfied: scipy>=1.5 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from dnplab) (1.6.3)
Collecting PyQt5<=5.14
  Using cached PyQt5-5.14.0.tar.gz (3.2 MB)
ERROR: PyQt5<=5.14 from https://files.pythonhosted.org/packages/7c/5b/e760ec4f868cb77cee45b4554bf15d3fe6972176e89c4e3faac941213694/PyQt5-5.14.0.tar.gz#sha256=0145a6b7de15756366decb736c349a0cb510d706c83fda5b8cd9e0557bc1da72 (from dnplab) has a pyproject.toml file that does not comply with PEP 518: 'build-system.requires' contains an invalid requirement: 'sip >=5.0.1 <6'
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the 'c:\users\user\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.

C:\Users\user>pip3 install sip
Requirement already satisfied: sip in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (6.1.0)
Requirement already satisfied: toml in c:\users\user\appdata\roaming\python\python39\site-packages (from sip) (0.10.2)
Requirement already satisfied: packaging in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from sip) (20.9)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from packaging->sip) (2.4.7)
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the 'c:\users\user\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.

**Comment by thcasey3** [comment]
@ehuang94 we apologize, pyqt5 is required only for the hydrationGUI and was supposed to be removed from the initial installation requirements. For now, try to install PyQt5 before dnplab:

```pip install pyqt5==5.14.0```
once that finishes, 
```pip install dnplab```

**Comment by Alex-Linhares** [comment]
getting the same here, even after installing dnplab:

`ERROR: pyqt5==5.14.0 from https://files.pythonhosted.org/packages/7c/5b/e760ec4f868cb77cee45b4554bf15d3fe6972176e89c4e3faac941213694/PyQt5-5.14.0.tar.gz#sha256=0145a6b7de15756366decb736c349a0cb510d706c83fda5b8cd9e0557bc1da72 has a pyproject.toml file that does not comply with PEP 518: 'build-system.requires' contains an invalid requirement: 'sip >=5.0.1 <6'
`
