### ISSUE TITLE
Enhancement calculation return wrong dimension of array

### ISSUE THREAD

**Issue by thorstenmaly** [DNPLab/DNPLab#147]
Workflow:
* Importing 2D TopSpin data set
* Process data
* Define integration region
* Calculate enhancements

when printing the workspace the dims for enhancements seem to be wrong
----------------
|'enhancements'|
----------------
values:
	19 ndarray (float64)
dims:
	[['PdBm']]
coords:
	nddata_coord_collection([array([-99.,   0.,   2., ...,  30.,  32.,  34.])])
attrs:

**Comment by thcasey3** [comment]
@thorstenmaly what would you expect for dims in this case?

**Comment by thorstenmaly** [comment]
I think dims is not correct: [['PdBm']]. Why are there two sets of square brackets?
It I try to plot this I get an error. Thomas had the same issue. I'll post the error when I get back to that.

**Comment by thcasey3** [comment]
I see. dnpdata is returning a list of a list for some reason, @tkeller12 should be a quick fix
