### ISSUE TITLE
Importing 2D topspin data fails when vdlist is not same length as td in the 2nd dimension

### ISSUE THREAD

**Issue by ktagami** [DNPLab/DNPLab#148]
**What happened**:
When DNPlab import function is used on 2d topspin data, the import fails when the length of the vdlist in topspin does not match the length of the 2nd dimension of the topspin data. Additionally setting the TD option in dnpimport.load does not fix the problem.

**What you expected to happen**:

**Minimal Complete Verifiable Example**:
data = dnp.dnpImport.load('100', TD = 11)

ValueError: TD in second dimension may not match len(VDLIST), try TD=<insert your TD> argument

```python
# Put your MCVE code here
```

**Anything else we need to know?**:

**Environment**:

<details><summary>Output of <tt>pip show dnplab</tt></summary>

</details>

**Comment by thcasey3** [comment]
@ktagami and @tkeller12  if not the length of the VDLIST, what parameter sets the size of the second dimension? I thought you set the number of scans in the second dimension to an even multiple of the length of the VDLIST and it runs through the VDLIST [n scans] / [len(VDLIST)] times and averages?

**Comment by ktagami** [comment]
> @ktagami and @tkeller12 if not the length of the VDLIST, what parameter sets the size of the second dimension? I thought you set the number of scans in the second dimension to an even multiple of the length of the VDLIST and it runs through the VDLIST [n scans] / [len(VDLIST)] times and averages?

@thcasey3 there is a parameter "TD" that sets the length of both the first and second dimensions. I just checked and this parameter is in the file "acqu" and "acqu2", the TD parameter in "acqu2" is the length of the 2nd dimension. The VDLIST is there for T1 experiments but is not necessary for other 2D experiments such as COSY ect.

**Comment by thcasey3** [comment]
@ktagami ok, I think I see what is happening. The topspin import doesn't use the acqu2 file, but assumes the second dimension is set by the length of the VDLIST. We will fix this.
