### ISSUE TITLE
[Feature-Request]: Import .dat or .mat format data

### ISSUE THREAD

**Issue by ktagami** [DNPLab/DNPLab#149]
**Is your feature request related to a problem? Please describe.**

Sometimes it is more convenient to save specman data as ascii (.dat) or .mat formats to easier access it in other programs (rather than the binary d01 format). 

**Describe the solution you'd like**

The ability to load alternative specman data formats with dnpImport.load()

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by thcasey3** [comment]
@ktagami can you give an example of how a .dat file might be structured when exported from specman? For the .mat file I can easily make a set of rules for users to follow when structuring their workspace so that dnplab can apply these rules and read the data properly. However, for an ascii, if I make a set of rules and then you need to restructure the ascii after exporting from specman to match these rules, that would be inconvenient. If the structure of the specman ascii is sensible I will use it to set the ascii structure rules.

**Comment by thcasey3** [comment]
@ktagami for this type of import function it would require a set of formatting rules that would not be general and may result in the same amount of upfront work to get the data into the correct format as would be needed to create the dnpdata object manually. What you could do is use any library you like to import your .mat or .txt file and arrange it properly to create a dnpdata object using:
``` data = dnplab.dnpData.dnpdata(values, coords, dims, attrs)```
This will create the same object that would've been created by importing the data.
The inputs are: values, a 1, 2, or 3 dimensional numpy array. coords, a list of numpy arrays (one for each dimension). dims, a list of dimension names equal in length to the number of dimensions. attrs, a dictionary of attributes you would like to carry around with the data. (*There are some attrs that are required for certain functions. For example, "convert_to_ppm" option won't work without attrs["nmr_frequency"], you'll get a warning and the axis won't be converted).

**Comment by tkeller12** [comment]
We will add an example showing how to read an ascii file and convert this to DNPLab format.

**Comment by tkeller12** [comment]
We can now import Specman data, but need to include compatibility for matplab data. Scipy has a function for importing .mat files.

**Comment by tkeller12** [comment]
Right now we don't have a user interested in importing matlab files. We will open this issue again if more users request this feature.
