### ISSUE TITLE
dnpTools.integrate doesnt work on 3D data sets (imported from specman)

### ISSUE THREAD

**Issue by ktagami** [DNPLab/DNPLab#150]
**What happened**:
When trying to integrate a 3D file (transient, x, y) I get an error.

local variable 'indirect_coords' referenced before assignment

**What you expected to happen**:

**Minimal Complete Verifiable Example**:
import dnplab as dnp
import numpy as np
file_name_path = "2D_Nutation.d01"
ws = dnp.dnpImport.load(file_name_path)
ws.values = np.abs(ws.values)
dnp.dnpTools.integrate(ws,'t')

```python
# Put your MCVE code here
```

**Anything else we need to know?**:

**Environment**:

<details><summary>Output of <tt>pip show dnplab</tt></summary>

</details>

**Comment by thcasey3** [comment]
@ktagami the integrate function currently doesn't handle 3D data but this can be added
