### ISSUE TITLE
Error computing (ODNP) hydration results using hydration function

### ISSUE THREAD

**Issue by thomasrwebber** [DNPLab/DNPLab#164]
**What happened:** Received a KeyError: 'T1_array' when computing (ODNP) hydration parameters (following example from http://dnplab.net/dnpHydration.html). After inputting my parameters, creating the workspace, and adding the hydration inputs, the error occurs when I perform the dnp.dnpHydration.hydration function. 

**What you expected to happen:** I expected store the hydration results in a variable by using the dnp.dnpHydration.hydration function. Then I can output all of my results.

**Minimal Complete Verifiable Example:**

```
Enhancements = [  1.0, 0.98141784, 0.46168687, 0.26564265, -0.13418087, -0.33061542, -1.29098063, -1.99342208, -3.34083857, -5.40446464, -9.06106296, -11.26843286, -15.16326875, -20.21460989, -24.64988148, -30.06889385, -34.61541456, -40.11077169, -42.69377044]                      # list of signal enhancements
Enhancement_powers = [0, 0.001, 0.0016, 0.0025, 0.004, 0.0063, 0.01, 0.0158, 0.0251, 0.0398, 0.0631, 0.1, 0.1580, 0.251, 0.398, 0.631, 1, 1.58, 2]           # list of signal enhancements powers in Watts
T1 = [1.31297, 1.52388, 1.78875]                 # list of T1 values in seconds
T1_powers = [0.1, 1.0, 2.0]              # list of T1 values powers in Watts

pars = {}                              # initialize the input parameters dictionary
pars['T10'] = 1.3                      # T1(0) value in seconds, i.e. T1 measured with power=0    ## THIS WAS NOT MEASURED ##
pars['T100'] = 2.3040                  # T10(0) value in seconds, i.e. T1 measured with SL=0 and power=0
pars['spin_C'] = 1000.0                # spin concentration in micromolar
pars['field'] = 3480.7                 # magnetic field in mT
pars['smax_model'] = 'free'            # choice of smax model, 'tethered' or 'free'
pars['t1_interp_method'] = 'second_order'    # choice of interpolation, 'linear' or 'second_order'

hydration = {
             'E' : np.array(Enhancements),
             'E_power' : np.array(Enhancement_powers),
             'T1' : np.array(T1),
             'T1_power' : np.array(T1_powers),
             'T10': pars['T10'],
             'T100': pars['T100'],
             'spin_C': pars['spin_C'],
             'field': pars['field'],
             'smax_model': pars['smax_model'],
             't1_interp_method': pars['t1_interp_method']
            }

hydration_workspace = dnp.create_workspace()
hydration_workspace.add('hydration_inputs', hydration)
hydration_results = dnp.dnpHydration.hydration(hydration_workspace)

```
**Environment**:

<details><summary>Output of <tt>pip show dnplab</tt></summary>

Name: dnplab
Version: 1.0.6
Summary: DNPLab - Bringing the Power of Python to DNP-NMR Spectroscopy
Home-page: http://dnpLab.net
Author: DNPLab Team
Author-email: None
License: MIT
Location: c:\users\thoma\anaconda3\lib\site-packages
Requires: numpy, h5py, matplotlib, scipy
Required-by:

</details>

**Comment by thcasey3** [comment]
This is due to a key change in the hydration inputs dictionary, the example you are using an old example. Change your hydration inputs to:
```
hydration = {
             'E_array' : np.array(Enhancements),
             'E_powers' : np.array(Enhancement_powers),
             'T1_array' : np.array(T1),
             'T1_powers' : np.array(T1_powers),
             'T10': pars['T10'],
             'T100': pars['T100'],
             'spin_C': pars['spin_C'],
             'field': pars['field'],
             'smax_model': pars['smax_model'],
             'interpolate_method': pars['t1_interp_method']
            }
```

**Comment by thomasrwebber** [comment]
Thanks Tom. That does fix the T1_array KeyError, but now I have a KeyError for 'interpolate_method'

**Comment by thcasey3** [comment]
ah sorry, missed that one. change that to ```interpolate_method```. you can check the examples in the latest release, I see now the docs website needs to be updated.

**Comment by thomasrwebber** [comment]
That worked! Thanks Tom. And yeah, updating the documentation would be great! (Although I think I'm the only one using the hydration example right now... others will soon :) )

**Comment by thcasey3** [comment]
ok good, the most recent example is correct, its the online documentation that us still incorrect. this will be fixed in the next update of the docs
