### ISSUE TITLE
phasecycle function not complete, doesn't support workspaces

### ISSUE THREAD

**Issue by thcasey3** [DNPLab/DNPLab#166]
- The phasecycle function doesn't handle workspaces the way other functions do
- The naming convention is inconsistent, should probably be "phase_cycle"
- There is an unnecessary line ```data = data.copy()```
- "dim not in dims" error isn't needed within the function

**Comment by tkeller12** [comment]
Processing functions will no longer operate on workspaces in DNPLab 2.0
