### ISSUE TITLE
docs site dnplab.net should be updated concurrent with releases

### ISSUE THREAD

**Issue by thcasey3** [DNPLab/DNPLab#167]
dnplab.net is version 1.0.4, package is 1.0.6. The docs site should always be updated concurrent with any release to reflect any fixes/updates in docstrings or examples

**Comment by thorstenmaly** [comment]
This is fixed now. The documentation is automatically created when pushed to develop or release branch. Documentation that is created in the develop branch is first uploaded to a staging website.
