### ISSUE TITLE
some functions don't support 3D (or ndim) data

### ISSUE THREAD

**Issue by thcasey3** [DNPLab/DNPLab#168]
Some functions still only support 1D or 2D data. 
We need to decide how to support 3D data, I propose that for any data with more than 2 dimensions either 1) user definition of ```dim``` and ```indirect_dim``` or 2) ```dim``` can be a list of dimensions with ```dim[0]``` being the direct and ```dim[1]``` the indirect.

**Comment by tkeller12** [comment]
This is resolved in DNPLab 2.0
