### ISSUE TITLE
A missing argument in exponential_fit() in the latest version of develop branch  

### ISSUE THREAD

**Issue by ehuang94** [DNPLab/DNPLab#169]
fit0 = dnp.exponential_fit(data_integrate0, dim = 't1', type = 'bi', initial_guess = t1_initial_guess)
TypeError: exponential_fit() got an unexpected keyword argument 'initial_guess'

The initial_guess is missing.

**Comment by thcasey3** [comment]
@ehuang94 the correct argument is ```p0=``` in accordance with ```scipy.optimize.curve_fit```. We are sorry the doc website is not updated, this is in the latest docstring and should show in the documentation when it is updated.
