### ISSUE TITLE
Some Features in Manual Alignment

### ISSUE THREAD

**Issue by ehuang94** [DNPLab/DNPLab#170]
1. Reference Spectrum: It would be great if users can define the reference to align peaks. 
2. If users want to manually align the spectrum one by one, they have to create a loop and extract the spectrum every time. Here is my example:

def manual_align_t1(data):
    iy = 0
    while iy <= np.size(data.coords['t1'])-1:
        result = dnp.manual_align(data['t1', iy, 'Average', 0:2].sum('t1'), dim = 'Average')
        data._values[:,iy,0:2] = result.values[:,0:2]
        result = dnp.manual_align(data['t1', iy, 'Average', 1:3].sum('t1'), dim = 'Average')
        data._values[:,iy,1:3] = result.values[:,0:2]
        result = dnp.manual_align(data['t1', iy, 'Average', 2:4].sum('t1'), dim = 'Average')
        data._values[:,iy,2:4] = result.values[:,0:2]
        figure('T1 Manual Alignment Result t1: %s' %(iy))
        dnp.plot(data['t1',iy ].sum('Average'))
        show()
        iy += 1
    return data

I will suggest having a new argument in manual alignment that users can define whether they align the data based or not based on peak drifting.

**Comment by tkeller12** [comment]
@ehuang94 will try to update the widget

**Comment by tkeller12** [comment]
This issue will not be fixed
