### ISSUE TITLE
[Feature-Request]: Feature-ndalign/align_linewidth/average

### ISSUE THREAD

**Issue by ehuang94** [DNPLab/DNPLab#178]
Poor signal-to-noise (especially when the microwave is off) is difficult data to align. Add an average function or a window linewidth function might solve this problem. 

Two ways:
1. np.convolve(a, v, type)
2. dnpNMR.window

**Comment by tkeller12** [comment]
We should add the ability to align specta with much larger line broadening. Add a function that returns the "index" value to shift spectra.

**Comment by tkeller12** [comment]
The current alignment function should be updated to take advantage of new fold and unfold methods of DNPData class.

**Comment by tkeller12** [comment]
Also, we should look at 2d cross-correlation functions in sci-py. Make sure this is backwards compatible. Default to new method, but allow old method with argument.

**Comment by tkeller12** [comment]
This is a related issue #254

**Comment by ehuang94** [comment]
unfold/fold applied

**Comment by ehuang94** [comment]
There is another issue for the 'average' issue. This issue can be closed.
