### ISSUE TITLE
Issue Importing WinEPR Files

### ISSUE THREAD

**Issue by ktagami** [DNPLab/DNPLab#179]
**What happened**:

When dnp.dnpImport.load was used on a .spc file generated from winepr an error occured. This occured with multiple data files so it seems to not be a corrupted data file issue.

**What you expected to happen**:

**Minimal Complete Verifiable Example**:
data = dnp.dnpImport.load('Tempo1.spc', data_type = 'winepr')

ValueError: could not convert string to float: 'S  3.000e+000'

```python
# Put your MCVE code here
```

**Anything else we need to know?**:

**Environment**:

<details><summary>Output of <tt>pip show dnplab</tt></summary>

</details>

**Comment by tkeller12** [comment]
Hi Kan, This issue should be resolved in the new release of DNPLab schedule for tomorrow.
