### ISSUE TITLE
[Feature Request] Enhancement Maximum and Fit in dnp.dnpNMR.calculate_enhancement

### ISSUE THREAD

**Issue by ehuang94** [DNPLab/DNPLab#185]
The function, dnp.calculate_enhancement, is working well but returns the enhancements integrals or ampltiude points only. It would be a good idea to return fit curves, enhancement maximum, and p half.

**Comment by thcasey3** [comment]
@ehuang94 ```dnpNMR.calculate_enhancement``` doesn't fit anything. It's just a ratio of integrals or amplitudes to a "p0" integral or amplitude. You can get the maximum with either:
```workspace["enhancements"].values.max``` (complex) or 
```workspace["enhancements"].real.values.max``` (just real part)

Can you post an example of how you were using it and explain what you expected?

**Comment by thcasey3** [comment]
@ehuang94 maybe you meant ```dnpFit.enhancement_fit```? This function returns the ```E_max``` and ```power_half``` along with the ```E_max_stdd``` and ```power_half_stdd``` as ```attrs``` of the ```["fit"]``` object.

**Comment by tkeller12** [comment]
This issue is outdated and will be removed.
