### ISSUE TITLE
Base line correction

### ISSUE THREAD

**Issue by thorstenmaly** [DNPLab/DNPLab#192]
We should have one function for baseline correction of spectra, no matter whether this is an FID, or an NMR spectrum or an EPR spectrum.
The function should accept the dnpData object as input, the order of the polynome (0, 1, 2 ...). These are the minimum parameters. Optionally, the user can define a region (probably just the index to make things easier) to calculate the offset based on. Also allow multiple regions to calculate the offset on. For example for an EPR spectrum it should be possible to calculate the offset based on the first few points and the last few points.

**Comment by tkeller12** [comment]
This is now implemented in DNPLab 2.0
