### ISSUE TITLE
import modules are inconsistent

### ISSUE THREAD

**Issue by thcasey3** [DNPLab/DNPLab#2]
the import modules each take a different number and type of inputs. All import modules should have the same style of inputs:

```
data = .import(path, par1=None, par2=True, par3='fid', etc.)
```

We should consider a unified import module that applies necessary import functions based on file type, rather than individual submodules. Either have it auto-detect based on file extensions, or have something like:

```
data = .import(path, type='topspin', par2=True, par3=None, etc.)
```

wrapper could be:
```
if type is "topspin":
   topsin code
elif type is "prospa":
   prospa code

etc.
```

**Comment by ylin00** [comment]
This will be closed by #44
