### ISSUE TITLE
DNP lab Naming Conventions

### ISSUE THREAD

**Issue by ktagami** [DNPLab/DNPLab#202]
**Is your feature request related to a problem? Please describe.**
I have been using DNP lab for about a year now and it is a very useful tool. However throughout the various updates it seems like naming conventions and subpackage names keep getting changed. This can be a bit annoying because each new version of DNPlab will break my old code and I have to dig through the .py files to find whats wrong. For example "dnp.dnpImport.load" changed to "dnp.load" without any indication in the documentation along with other functions such as "create_workspace". Also it seems like the default naming conventions for axes  has changed a few times throughout various updates (i.e "t1", "f1" ect.). I understand if this is on purpose and is converging to a more optimal solution, but I just wanted to bring it to your attention. But overall this is a very useful package keep up the good work.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by thorstenmaly** [comment]
Hi Kan, release of our version 2.0 was a big step. We learned a lot since we started developing the package and we are very hopeful that we are approaching a stable version of the code, so we avoid breaking code every time we fixed a bigger issue.
Thanks for your support.
