### ISSUE TITLE
[Feature-Request]: DNPLab core functions should have examples in docstring

### ISSUE THREAD

**Issue by thorstenmaly** [DNPLab/DNPLab#205]
Add examples to docstrings of core functions, such as fft, appodization, load, save etc.

**Comment by tkeller12** [comment]
For example:
fourier_transform(data, dim='t2', zero_fill_factor=1, shift=True, convert_to_ppm=True)
    Perform Fourier Transform down dim dimension given in proc_parameters

    .. Note::
        Assumes dt = t[1] - t[0]

    .. math::


    Args:
        all_data (dnpdata, dict): Data container

    +------------------+------+-----------+--------------------------------------------------+
    | parameter        | type | default   | description                                      |
    +==================+======+===========+==================================================+
    | dim              | str  | 't2'      | dimension to Fourier transform                   |
    +------------------+------+-----------+--------------------------------------------------+
    | zero_fill_factor | int  | 2         | factor to increase dim with zeros                |
    +------------------+------+-----------+--------------------------------------------------+
    | shift            | bool | True      | Perform fftshift to set zero frequency to center |
    +------------------+------+-----------+--------------------------------------------------+
    | convert_to_ppm   | bool | True      | Convert dim from Hz to ppm                       |
    +------------------+------+-----------+--------------------------------------------------+

    Returns:
        dnpdata: data object after FT
