### ISSUE TITLE
[Feature-Request]: Display processing attributes in human readable from

### ISSUE THREAD

**Issue by thorstenmaly** [DNPLab/DNPLab#207]
DNPLab stores the processing parameters for each step.
Add a process to display the processing steps and parameters in a human readable form.
Should go to reporting.

**Comment by tkeller12** [comment]
Add some documentation on how to show this.

**Comment by tkeller12** [comment]
@ehuang94 Will work on this function. Print with attribute on left and value on right.

**Comment by ehuang94** [comment]
This is what I got. 

-----------------
proccessing steps
-----------------
window: kind=exponential, lw=4.0
fourier_transform: dim=t2, zero_fill_factor=2, shift=True, convert_to_ppm=True
phasecycle: dim=Average, receiver_phase=0 1 2 3
ndalign: dim=f2
autophase: method=search, reference_range=None, reference_slice=None, force_positive=False, order=zero, pivot=0, delta=0
remove_background: dim=f2, deg=0, regions=None
None

**Comment by tkeller12** [comment]
Implement new show_attrs function to display all attrs.
proc_attrs, exp_attrs, import_attrs, attrs
By default all should be shown, but flag can be set to select each.
Yen-Chun will demo next week.

**Comment by ehuang94** [comment]
Added two functions:
attrs_info()
show_attrs()

**Comment by ehuang94** [comment]
1. The functions showing the attributes are: proc_info(), exp_info().
2. show_attrs() is the function to operate the above functions based on the flag
3. The proc_info is a dictionary now.

**Comment by ehuang94** [comment]
Huge changes applied to:

Prospa 
Topspin
Bes3t
H5

These are now accessible to dnplab attributes

**Comment by tkeller12** [comment]
Yen-Chun should demonstrate his show attrs function and submit a pull request when completed
