### ISSUE TITLE
[Feature-Request] DNPLab list of attributes

### ISSUE THREAD

**Issue by tkeller12** [DNPLab/DNPLab#215]
Create list of attributes

**Comment by thorstenmaly** [comment]
Number of transients missing for NMR spectra

**Comment by tkeller12** [comment]
An excel sheet of attributes has been started.

**Comment by tkeller12** [comment]
We need to decide which experimental parameters will receive a reserved attribute name.

**Comment by ehuang94** [comment]
new pull request started

**Comment by ehuang94** [comment]
The new pull request has been approved.
