### ISSUE TITLE
[Bug]: Apodization - Return different error message

### ISSUE THREAD

**Issue by thorstenmaly** [DNPLab/DNPLab#218]
When trying to apply apodization to a spectrum that is already fourier transformed there error returned is: "ValueError: 't2' is not in list"

We should have a more customized error message saying that apodization can only be applied to time domain data before fourier transformation. 
Alternatively, if frequency domain data is used, we could do a inverse FT, apply the line broadening and FT the data back.

**Comment by thorstenmaly** [comment]
Actually, not sure what happens if dims is "f1"? We need to check that this is working.

**Comment by tkeller12** [comment]
To perform apodization down a different dimension, use the "dim" argument. More detailed error messages should be given.

**Comment by tkeller12** [comment]
I can add a customized error message.

**Comment by tkeller12** [comment]
This has been resolved in pull request #346
