### ISSUE TITLE
Gaussian window function returns incorrect data

### ISSUE THREAD

**Issue by thorstenmaly** [DNPLab/DNPLab#219]
Check the gaussian apodization function. It returns completely different results compared to the exponential window function when using the same linewidth.

**Comment by tkeller12** [comment]
The gaussian apodization has been fixed

**Comment by thorstenmaly** [comment]
There still seems to be an issue with the definition of the linewidht. It is not consistent with how it is defined for the exponential apodization window

**Comment by tkeller12** [comment]
Linewidth argument now corresponds to exactly to linewidth in Hz
