### ISSUE TITLE
Difference between align and ndalign

### ISSUE THREAD

**Issue by thorstenmaly** [DNPLab/DNPLab#226]
What is the difference between align and ndalign? Do we need both? Can the two functions be combined?

**Comment by tkeller12** [comment]
The plan is to eventually combine these into one function. Right now "ndalign" is the function that should be used. The difference between the functions is how the alignment behaves with 3d and higher dimensional data.

**Comment by tkeller12** [comment]
Align function should be depreciated. The ndalign function is working with N-dimensional data and should be used instead.

**Comment by tkeller12** [comment]
In 3 months, the align function will be removed. 01/01/2023

**Comment by tkeller12** [comment]
Added a depreciation warning to the align function
