### ISSUE TITLE
[Feature-Request]: unittests missing

### ISSUE THREAD

**Issue by thcasey3** [DNPLab/DNPLab#228]
unittests for functions that had major changes in v2 no longer have assertions. I suspect this is why one of the analysis examples is broken yet pull requests still pass all checks

**Comment by tkeller12** [comment]
We should review the way tests are performed in scipy and numpy and write similar tests.

**Comment by ehuang94** [comment]
H5 file loading/saving test should be added, too.

**Comment by tkeller12** [comment]
We have now added unittests for most functions
