### ISSUE TITLE
[Bug] TypeError Shown when Doing data /= np.max(data.values)

### ISSUE THREAD

**Issue by ehuang94** [DNPLab/DNPLab#239]
The data values cannot be divided:

`data /= np.max(data.values)
`

It shows the error message: 

    data /= np.max(data.values)
  File "c:\users\yen-chun huang\documents\repositories\dnplab\dnplab\core\base.py", line 411, in __truediv__
    raise TypeError("Cannot add type: {}".format(type(b)))
TypeError: Cannot add type: <class 'numpy.float32'>

**Comment by thcasey3** [comment]
@ehuang94 I can't reproduce this error. Can you provide a little more info? Specifically, data.version, data.values.dtype, and data.values.shape. Also, can you try `data.values /= data.values.max()`?

**Comment by tkeller12** [comment]
@ehuang94 Can you please include a detailed example that reproduces this error?

**Comment by tkeller12** [comment]
Try creating specific numpy arrays with defined types and divide dnpdata object by that type.
>>> import numpy as np
>>> a = np.r_[1:10]
>>> a.astype('float32')
array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

**Comment by ehuang94** [comment]
cannot re-produce the issues anymore

**Comment by ehuang94** [comment]
The issue is found again when I am processing EPR data and trying to normalize the maximum to 1.

The data is .spc file.

Here is an example:

`epr_data_file = '../data/Data Schlumberger/Crude Oil Data/Sample5_20191210a.spc'`
`epr_data = dnp.load(epr_data_file)`
`epr_data /= np.max(epr_data)`

The error came out. 

......documents\repositories\dnplab\dnplab\core\base.py in __truediv__(self, b)
    410             return a
    411         else:
--> 412             raise TypeError("Cannot add type: {}".format(type(b)))
    413 
    414     def __rtruediv__(self, b):

TypeError: Cannot add type: <class 'numpy.float32'>

**Comment by ehuang94** [comment]
This is working in the develop_tk branch.
