### ISSUE TITLE
[Bug] Cannot save dictionary in as an h5 file

### ISSUE THREAD

**Issue by ehuang94** [DNPLab/DNPLab#240]
The dictionary cannot be saved in an h5 file.

```
import dnplab as dnp
info = {'info', 1}
dnp.save(info, '../1.h5', overwrite = True)
```

The error message is:
    raise TypeError(
TypeError: object format not recognized, must be dnpdata or dnpdata_collection

**Comment by tkeller12** [comment]
We need a better example/documentation for saving a dictionary in h5 file

**Comment by tkeller12** [comment]
This is already implemented. What is not currently allowed is saving recursive dictionaries in h5 files.
