### ISSUE TITLE
[Bug Report] dnp. returns some functions that shouldn't be in core function list  

### ISSUE THREAD

**Issue by ehuang94** [DNPLab/DNPLab#247]
dnp. returns some functions such as dnp.curve_fit() or dnp.show(). Are these functions should be in the core function list?

**Comment by tkeller12** [comment]
There is a way to define the functions inside a module with the __all__ variable. This should be used for each module.

**Comment by tkeller12** [comment]
Can you try this again with the current version and list any unwanted functions in the dnp. namespace.

**Comment by tkeller12** [comment]
Currently dir(dnp) returns:
['DNPData', 'DNPLAB_CONFIG', 'N_A', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'align', 'align_widget', 'analysis', 'apodization', 'apodize', 'autophase', 'autophase_dep', 'average', 'bStencil', 'background', 'bes3t', 'c', 'cStencil', 'calc_conversion_factor', 'calc_tp90', 'calculate_enhancement', 'cnsi', 'concat', 'config', 'constants', 'conversion', 'convert_power', 'core', 'create_complex', 'cumtrapz', 'cumulative_integrate', 'curve_fit', 'cycler_list', 'dBm2w', 'delta', 'dnp_remove_background', 'eV', 'e_charge', 'e_gyro', 'epsilon_0', 'fStencil', 'fancy_plot', 'fft', 'find_peaks', 'fit', 'fitting', 'forwarded_pyplot_plots', 'fourier_transform', 'general', 'generate_data', 'get_slice', 'gmrProperties', 'h', 'h5', 'hbar', 'helpers', 'hydration', 'image', 'implements_np', 'imshow', 'integrate', 'integration', 'interp', 'interpolation', 'inverse_fourier_transform', 'inversion_recovery_fit', 'io', 'key', 'left_shift', 'lineshape', 'load', 'load_csv', 'm_e', 'math', 'mrProperties', 'mr_properties', 'mu_0', 'mub', 'mub_Hz', 'ndalign', 'normalize', 'np', 'offset', 'optimize', 'p_gyro', 'peak_info', 'phase', 'phase_cycle', 'phase_widget', 'pi', 'plot', 'plotting', 'plt', 'power', 'processing', 'prospa', 'pseudo_modulation', 'radicalProperties', 'radical_properties', 'random', 'reference', 'relaxation', 'remove_background', 'reporting', 'save', 'savgol_filter', 'scipy', 'show', 'show_dnp_properties', 'signal_to_noise', 'sim_dnp_profile', 'smooth', 'specman', 'stack', 'stack_plot', 'tnmr', 'topspin', 'trapz', 'update_axis', 'value', 'version', 'vna', 'vnmrj', 'w2dBm', 'warn', 'warnings', 'waterfall', 'widgets', 'window', 'winepr']

**Comment by tkeller12** [comment]
You can use __all__ to restrict functions which are imported.

**Comment by tkeller12** [comment]
Looks like issue is resolved.

**Comment by tkeller12** [comment]
Current namespace:
`['DNPData', 'DNPLAB_CONFIG', 'N_A', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'align', 'align_widget', 'analysis', 'apodization', 'apodize', 'autophase', 'autophase_dep', 'average', 'background', 'bes3t', 'c', 'calc_conversion_factor', 'calc_tp90', 'calculate_enhancement', 'cnsi', 'concat', 'config', 'constants', 'conversion', 'convert_power', 'core', 'create_complex', 'cumulative_integrate', 'curve_fit', 'dBm2w', 'decay2Ce', 'delta', 'eV', 'e_charge', 'e_gyro', 'epsilon_0', 'fancy_plot', 'fft', 'find_peaks', 'fit', 'fitting', 'fourier_transform', 'general', 'generate_data', 'get_slice', 'gmrProperties', 'h', 'h5', 'hbar', 'helpers', 'hydration', 'image', 'implements_np', 'imshow', 'integrate', 'integration', 'interp', 'interpolation', 'inverse_fourier_transform', 'inversion_recovery_fit', 'io', 'key', 'left_shift', 'lineshape', 'load', 'load_csv', 'm_e', 'math', 'mrProperties', 'mr_properties', 'mu_0', 'mub', 'mub_Hz', 'ndalign', 'normalize', 'offset', 'optimize', 'p_gyro', 'peak_info', 'phase', 'phase_cycle', 'phase_widget', 'pi', 'plot', 'plotting', 'plt', 'power', 'processing', 'prospa', 'pseudo_modulation', 'radicalProperties', 'radical_properties', 'random', 'reference', 'relaxation', 'remove_background', 'reporting', 'save', 'show', 'show_dnp_properties', 'signal_to_noise', 'sim_dnp_profile', 'smooth', 'specman', 'stack', 'stack_plot', 'tnmr', 'topspin', 'tp90_B1', 'update_axis', 'value', 'version', 'vna', 'vnmrj', 'w2dBm', 'warn', 'warnings', 'waterfall', 'widgets', 'window', 'winepr']`
