### ISSUE TITLE
Difference between background and remove_background?

### ISSUE THREAD

**Issue by thorstenmaly** [DNPLab/DNPLab#257]
- What is the difference between the two functions?
- remove_background calls background. Either remove background (remove_background is more descriptive) or make background a private function

**Comment by tkeller12** [comment]
Return background function and dnpdata object if argument "return_background" is True in "background" function.

**Comment by tkeller12** [comment]
This could be made similar to "fit" function

**Comment by tkeller12** [comment]
We will keep "remove_background"

**Comment by thorstenmaly** [comment]
We need to resolve this. It is confusing and not intuitive.
