### ISSUE TITLE
[Feature Request] Change save to save_h5

### ISSUE THREAD

**Issue by thorstenmaly** [DNPLab/DNPLab#259]
Suggestion of changing save to save_h5.
save is not a general save function, it only saves dnpdata objects in h5 format and calling it save_h5 is more descriptive than just generically calling it save.

I suggest we rename save to save_h5 and for the meantime also create a wrapper function save that can be deprecated in the future.

We should also change

`def save(data_object, filename, save_type=None, *args, **kwargs):`

to 

`def save(data, filename, save_type=None, *args, **kwargs):`

to be consistent with the other functions of the package.

**Comment by tkeller12** [comment]
This would allow for multiple save formats

**Comment by Bkaribo** [comment]
there is already a save_h5 function

maybe the save function gets deprecated and we only use save_h5?

**Comment by tkeller12** [comment]
save function should default to "h5" file type

**Comment by tkeller12** [comment]
Documentation for save function should be updated

**Comment by tkeller12** [comment]
Check save_h5 for dnpdata handling

**Comment by tkeller12** [comment]
@Bkaribo Should submit a pull request for this issue. It should be already resolved

**Comment by Bkaribo** [comment]
as discussed this issue doesn't need a pull request
