### ISSUE TITLE
use recarray in DNPData objects?

### ISSUE THREAD

**Issue by Bkaribo** [DNPLab/DNPLab#303]
numpy recarrays provide a similar syntax as DNPData objects, maybe it is useful to check whether it makes sense to implement the values attribute in DNPData as recarray?
an advantage would be the now external functionality for __getitem__ in standard use cases, problematic is that the access to floating point values  still needs to be handled on its own.

another advantage is that many functions are already implemented on recarrays

https://numpy.org/doc/stable/reference/generated/numpy.recarray.html#numpy.recarray

**Comment by tkeller12** [comment]
I don't believe this supports n-dimensional arrays. The "names" argument denotes the names of columns, similar to a spreadsheet. We we need is something where the names of each dimension can be specified.
