### ISSUE TITLE
signal_to_noise function not consistent with other DNPLab function

### ISSUE THREAD

**Issue by thorstenmaly** [DNPLab/DNPLab#310]
Most DNPLab function return a DNPdata object. Here this would be just a single value. I don't remember if there is a function that would return two arguments. Just looking through the docu, I couldn't find another example:

Here is what we should change:
1) Return DNPdata object with the SNR value
2) Why does the user have to give a signal_region? Why not use the max. signal intensity by default if no region is given. If the user gives a region find value in that region
3) Can the user give multiple regions? What happens if user gives multiple regions?
4) Remove warning. Either the function is stable or not. If it is not stable it shouldn't be released.

**Comment by Bkaribo** [comment]
is now consistent with other functions
