### ISSUE TITLE
Hydration Parameters Calculating Issues

### ISSUE THREAD

**Issue by ehuang94** [DNPLab/DNPLab#323]
See the example in this link:
http://dnplab.net/auto_examples/02_Analysis/plot_03_analyze_odnp_data.html#sphx-glr-auto-examples-02-analysis-plot-03-analyze-odnp-data-py

**Issue 1 - k_rho calculating issue:**

In the function 'dnp.hydration()', k_rho is calculated based on the initial t1(0) values but not interpolated t1(0). This gives k_rho the value of 999.999 with the given values t1(0) = 2.0 and t100 = 2.5 shown in the example: 

**Issue 2 - hydration parameter coupling factor is not in the valid range:**

According to the paper. coupling factor should be within the range of 0.32 - 0.33. However, the example gives this value out of range.

**Comment by tkeller12** [comment]
The example has been removed.
