### ISSUE TITLE
Loading Error for SpecMan Dataset

### ISSUE THREAD

**Issue by ehuang94** [DNPLab/DNPLab#342]
When loading specman4D.d01 in the example dataset, the error is:

ValueError: cannot reshape array of size 1800000 into shape (4,1500,40,5,3)

**Comment by tkeller12** [comment]
The number of points is off by a factor of 2. This could be a data_type issue (e.g. int16 vs int32) or complex number issue.

**Comment by thorstenmaly** [comment]
This issue was fixed with the updated SpecMan load function
