### ISSUE TITLE
[Feature Request]: Print DNPLab version and path

### ISSUE THREAD

**Issue by thorstenmaly** [DNPLab/DNPLab#35]
We should have a function that returns the DNPLab version number and the installation path and whatever else is helpful to troubleshoot issues that may arise from using different versions.

**Comment by tkeller12** [comment]
Why do you need anything other than `dnplab.__version__` and `dnplab.__file__`?

**Comment by thorstenmaly** [comment]
We should have a convenient and intuitive way to report this information. No newcomer to DNPLab or python will guess this notation.

For example see what easyspininfo shows: 

>> easyspininfo
==================================================================
  Release:          5.2.25 (2019-02-19)
  Expiry date:      28-Feb-2021
  Folder:           /XXXX/XXXXX/XXXXX/MATLAB/Toolboxes/easyspin/easyspin
  MATLAB version:   9.8.0.1323502 (R2020a)
  Platform:         Darwin 19.6.0
  mex-files:        mexmaci64, ok
  System date:      09-Oct-2020 15:15:18
  Temp dir:         /XXXXXX
==================================================================

**Comment by ylin00** [comment]
The following comes from `pip show dnplab`. Is there additional info requested ?
```
> pip show dnplab
Name: dnpLab
Version: 1.0.1
Summary: dnpLab - Bringing the Power of Python to DNP-NMR Spectroscopy
Home-page: http://dnpLab.net
Author: dnpLab Team
Author-email: None
License: MIT
Location: /Users/<usrname>/opt/anaconda3/envs/<env>/lib/python3.7/site-packages
Requires: h5py, PyQt5, scipy, numpy, matplotlib
Required-by: 
```

**Comment by thorstenmaly** [comment]
Oh, that's fantastic. I'll add it to the documentation.
