### ISSUE TITLE
High First Order Phase Correction Results in zero ppm point data spectrum intensity becoming zero

### ISSUE THREAD

**Issue by rchaklashiya** [DNPLab/DNPLab#371]
**What happened**:
For a particular pseudo-2d dataset (DNP Profile) I found that I need to make the first order phase correction very high (>10,000) in order to remove wiggly baseline issues in the plotted 1D spectrum. However, when I do that, I get a weird issue where the zero ppm point of  the spectrum has its intensity go down to zero, for all spectra in the pseudo-2D dataset. This issue was reproduced in a 1D dataset in the same file folder (file 1, see attached). Interestingly, someone else in the lab who used data for a different nucleus (fluorine) did not have this same issue I'm having (for their 1D dataset) and I'm not sure why. They used the exact same code I'm using to do it.

A related issue is that I found that changing the pivot point doesn't really change the first order phase correction, nor does autophasing really work to make phasing good. I'm not sure how universal or general those issues are but I think those should be looked into to.

My dataset is here: [20230420_40mM_TFO_60_30_10_d6_DMSO_D2O_H2O_100K.zip](https://github.com/DNPLab/DNPLab/files/12044575/20230420_40mM_TFO_60_30_10_d6_DMSO_D2O_H2O_100K.zip)

**What you expected to happen**:
I expected to be able to go to high first order phase correction without having this weird spike down to zero intensity.
**Minimal Complete Verifiable Example**:

```python
# BUG REPORT
# %%_________________________________________________________________________
# Cell 1 - PACKAGE IMPORT STEP

import dnplab as dnp # imports dnplab package, callable as "dnp"
import HanLabTools as hlt # imports the HanLabTools package, callable as "hlt". Note that you WILL have issues if "HanLabTools" is not written in the exact form as written in those quotation marks
import os # imports the os package, useful for file operations
from pathlib import Path # imports the Path subpackage from the pathlib package, useful for file operations
import numpy as np # imports the numpy package, callable as "np", useful for mathematical operations
import matplotlib # imports the matplotlib package, useful for math and plotting
import matplotlib.pylab as plt # imports the pylab subpackage, callable as "plt", useful for simplifying code

# %%********************************************************************************
# Cell 2 - FID Processing Step
Path.home() 
file = 'Box/Raj_Han_Lab_Data/Data/NMR_300_Static/20230420_40mM_TFO_60_30_10_d6_DMSO_D2O_H2O_100K/700' # the filepath to your data folder, for AFTER the home directory piece. Please check what the home directory piece's error code prints BEFORE using this so you know where to start the filepath!
loadDir = Path.home()/file
startfreq = 193.1 # starting frequency
endfreq = 194.2 # ending frequency
data = hlt.import_data(loadDir, experiment_type = "DNPProfile_F", start_stop=[startfreq,endfreq])
numberofdummies = 20 # select number of dummy datasets to create. You can choose a low number (even 0) but note that if you do, you'll probably not have certain options to plot individual spectra down the line. Only select 0 if you're doing a 1D dataset

dataname = 'dnp_profile'
dummydata = []
i = 0
while i < numberofdummies:
    dummydata.append(hlt.import_data(loadDir, experiment_type = "DNPProfile_F", start_stop=[startfreq,endfreq]))
    i = i+1

# INPUT FID PARAMETERS HERE
lb = 0 # line broadening
ls = 0 # leftshift
fids2plot = 1 # for 2d data
customtitle = 'TFO' # add a custom title to the plot. This custom title will be used for all plots moving forward
showfull = True # if you want to see the full fid, set this to True. Otherwise, set to False and use maxshown
maxshown = 0.0002 # max time in seconds shown when looking at the fid here. Note that this does NOT cut the data. It just shows data up to a point

# CODE THAT EXECUTES THE FID PROCESSING
data = dnp.apodize(data,lw=lb) # executes line broadening (you only see a difference if you choose absurdly high values)
data = dnp.left_shift(data, dim='t2', shift_points=ls) # executes leftshift
data = dnp.remove_background(data) #executes background correction (not sure if it works on the fid???)
# A "dummy use counter" is now created to track how many times the dummy data is used before it's used up.
dummycounter = 0
i = dummycounter
while i < numberofdummies:
    dummydata[i] = dnp.apodize(dummydata[i],lw=lb)
    dummydata[i] = dnp.left_shift(dummydata[i], dim='t2', shift_points=ls)
    dummydata[i] = dnp.remove_background(dummydata[i])
    i = i + 1
# plots all fids
dnp.plt.figure()
dnp.plt.xlabel("time (s)") # sets up fid x axis label
dnp.plt.ylabel("intensity (a.u.)") # sets up fid y axis label
if not showfull:
    dnp.plt.xlim(0,maxshown) # sets up max fid timepoint shown
if date != '':
    dnp.plt.title(customtitle + " All FID's" +  ', ' + date) # sets up title if date is indicated in topspin filename
else:
    dnp.plt.title(customtitle + " All FID's") # sets up title if date is not indicated in topspin filename
dnp.plot(data)
dnp.plt.show()

# plots one chosen fid. There's some issue where this doesn't seem to work if you switch the order of this one and the previous one and I'm not sure why
dnp.plt.figure() # sets up fid figure
dnp.plt.xlabel("time (s)") # sets up fid x axis label
dnp.plt.ylabel("intensity (a.u.)") # sets up fid y axis label
if not showfull:
    dnp.plt.xlim(0,maxshown) # sets up max fid timepoint shown
#dnp.plot(data.select((fids2plot,fids2plot))) # if 2d data, plots the chosen fid. NOTE: dnplab cannot choose only one fid, can only choose two at minimum ??????????? The workaround here is to choose the same point twice, but this bug should def be reported. also, once you do this, you cannot go back to choosing any other fid or spectrum besides this slice. that's another seriously fatal issue for dnplab
if dummycounter < numberofdummies:
    dnp.plot(dummydata[dummycounter].select((fids2plot,fids2plot)))
    dummycounter = dummycounter + 1
else:
    print("ERROR: Ran out of dummy datasets! Please increase numberofdummies")
dnp.plt.show()
# %% CELL 3 - SPECTRUM PROCESSING STEP - ISSUE HAPPENS WHEN ph1 IS TOO HIGH, REGARDLESS OF PIVOTPOINT

# INPUT USER SPECTRUM PROCESSING PARAMETERS
# choose spectrum to plot, if 2D
spectra2plot = manualpoint # sets which spectrum to plot. can choose manualpoint or another point
# phase correction parameters
ph0 = 0.0 # zero order phase correction
ph1 = 10000 # first order phase correction <--THIS IS WHERE THE ISSUE IS
pivotpoint = 0 # pivot point for first order phase correction (needed for both autophase and manual phase). This would be a chemical shift value. Default is "None" but normally you would write a floating point number here
# spectrum window parameters
showfull = False # if you want to see the full spectrum, set this to True. Otherwise, set to False and use leftlim/rightlim
leftlim = -200 # left limit of what is shown on the graph
rightlim = 200 # right limit of what is shown on the graph
# set the plot title
customtitle = customtitle # sets it to be the same as for the previous cell if you set equal to "customtitle", otherwise you can change it here if you want

# CODE THAT EXECUTES SPECTRUM PROCESSING PARAMETERS
data = dnp.fourier_transform(data) # fourier transforms the fid into a spectrum
data = dnp.phase(data, p0=ph0,p1=ph1,pivot=pivotpoint) # manual phase correction, both zeroth and first order
i = dummycounter
while i < numberofdummies:
    dummydata[i] = dnp.fourier_transform(dummydata[i])
    dummydata[i] = dnp.phase(dummydata[i], p0=ph0,p1=ph1,pivot=pivotpoint) # manual phase correction, both zeroth and first order
    i = i + 1
# CODE THAT EXECUTES THE FID PROCESSING

# plots all spectra
dnp.plt.figure()
if date != '':
    plottitle = customtitle + " All Spectra" +  ', ' + date
else:
    plottitle = customtitle + " All Spectra"
if showfull:
    dnp.fancy_plot(data, title=plottitle)
else:
    dnp.fancy_plot(data,xlim=[leftlim,rightlim],title=plottitle)
dnp.plot(data)
dnp.plt.show()
# plots one chosen spectrum.
dnp.plt.figure() # sets up fid figure
if date != '':
    dnp.plt.title(customtitle + " Spectrum " + str(spectra2plot) + ', ' + date) # sets up title if date is indicated in topspin filename
else:
    dnp.plt.title(customtitle +  " Spectrum " + str(spectra2plot)) # sets up title if date is not indicated in topspin filename
if dummycounter < numberofdummies:
    if showfull:
        dnp.fancy_plot(dummydata[dummycounter].select((spectra2plot,spectra2plot)),title=plottitle)
    else:
        dnp.fancy_plot(dummydata[dummycounter].select((spectra2plot,spectra2plot)),xlim=[leftlim,rightlim],title=plottitle)
        print("dummycounter is " + str(dummycounter)) # error check
    dummycounter = dummycounter + 1
else:
    print("ERROR: Ran out of dummy datasets! Please increase numberofdummies in cell 2 part 4!")
dnp.plt.show()
#%%
```
Output plots look like this:
![image](https://github.com/DNPLab/DNPLab/assets/18043279/f8329e51-76b5-4468-abb2-b9b521dee7cb)
![image](https://github.com/DNPLab/DNPLab/assets/18043279/da2c5bcd-ddab-4125-b1be-404dd4092358)

**Anything else we need to know?**:
I'm trying to determine workarounds like manipulating the data such that that point disappears but I'm having a hard time because the data is formatted such that each vector consists of points from every fid rather than one fid--do you have any suggestions on how to get around that?
**Environment**:
C:\Windows\System32>pip show dnplab
Name: dnplab
Version: 2.1.4
Summary: DNPLab - Bringing the Power of Python to DNP-NMR Spectroscopy
Home-page: http://dnpLab.net
Author: DNPLab Team
Author-email:
License: MIT
Location: C:\Users\rajkc_n1emmcn\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires: h5py, matplotlib, numpy, scipy
Required-by:

C:\Windows\System32>pip show HanLabTools
Name: HanLabTools
Version: 0.2.3
Summary: Import tools for DNPLab specific to the Han Lab
Home-page: https://github.com/Bridge12Technologies/HanLabTools
Author: Thorsten Maly
Author-email: tmaly@bridge12.com
License:
Location: C:\Users\rajkc_n1emmcn\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires: numpy
Required-by:

</details>

**Comment by thorstenmaly** [comment]
Hi Raj,

the problem is not the phasing function, it was in the usage of the background removal function. When the remove_background function is used without any further input arguments, the offset is calculated as the average over all points. For an FID it is better to specify just the last portion (mainly noise) to be used to calculate the offset. This can be specified using the regions argument:

E.g.: `data = dnp.remove_background(data, regions = [(0.0006, 0.0010)])`

Below is a simplified version of your code. When executed, you will see that the issue with the 0 value at the center of the spectrum is gone.


One more comment about the appodization:
data = dnp.apodize(data,lw=lb) # executes line broadening (you only see a difference if you choose absurdly high values)

The value for the line broadening is given in Hz. Your line are very broad (short FID) and this will lead to large values for the line broadening to be effective.

`import dnplab as dnp
import HanLabTools as hlt

loadDir = "20230420_40mM_TFO_60_30_10_d6_DMSO_D2O_H2O_100K/700"

startfreq = 193.1
endfreq = 194.2
data = hlt.import_data(loadDir, experiment_type = "DNPProfile_F", start_stop=[startfreq,endfreq])

lb = 500                                                    # line broadening
ls = 85                                                     # leftshift

data = dnp.apodize(data,lw=lb)
data = dnp.left_shift(data, dim='t2', shift_points=ls)

data = dnp.remove_background(data, regions = [(0.0006, 0.0010)])

ph0 = 0
ph1 = 0
pivotpoint = 0 

data = dnp.fourier_transform(data)
data = dnp.phase(data, p0=ph0,p1=ph1,pivot=pivotpoint)

dnp.plt.figure()
dnp.plot(data)
dnp.plt.xlim(-200, 200)
dnp.plt.show()`

**Comment by rchaklashiya** [comment]
Hi Thorsten,

Apologies for getting back to you on this this late. I just tried your modified code but am now getting no spectrum--is there anything missing from what you are showing here? This is the output that I get when using your code (only adjusting for filepath):
![image](https://github.com/DNPLab/DNPLab/assets/18043279/5052f9db-d7c9-4f50-99cb-ad30153ae8e4)
