### ISSUE TITLE
Incorrect TopSpin Data Loading in the Example

### ISSUE THREAD

**Issue by ehuang94** [DNPLab/DNPLab#390]
The TopSpin data loading function was not implemented and documented appropriately. 

When loading the TopSpin data, the function will convert the raw data to complex depending on AQ_mod.

There are four AQ_mod from the manual: 

0: qf = single channel detection.
1: qseq = quadrature detection in sequential mode. 
2: qsim = quadrature detection in simultaneous mode. 
3: DQD = digital quadrature detection

However, it is unclear which AQ_mod the data needs to be converted to complex, and the current function leads to an incorrect spectrum after loading the TopSpin data.

Additional:

Removing group delay becomes an option in the function, is false by default, and has another name as an argument: remove_digital_filter. Should it be True by default and have a constant name?

**Comment by thorstenmaly** [comment]
remove_digital_filter and remove group delay does the same thing. We should stick with remove_digital_filter in the arguments and write in the description that this will deal with the group delay.

**Comment by ehuang94** [comment]
The complex data converter is doing the opposite way.

The AQ_mod 0 or 2 data doesn't need to be converted, and 1 or 3 does.
