### ISSUE TITLE
SpecMan First Point in First Column Not Correct Value

### ISSUE THREAD

**Issue by tkeller12** [DNPLab/DNPLab#393]
For SpecMan data, the first point in the first column of the imported data is 1.7936620e-43, which is not correct. All the other data seems to have the correct values.

Here is a minimal example:
```
import dnplab as dnp

data = dnp.load('230912/303file.d01')

print(data)
print(data.values)

dnp.plt.figure()
dnp.plot(data)
dnp.plt.show()
```
![SpecMan_First_Point_Issue](https://github.com/DNPLab/DNPLab/assets/65348833/1177aedf-7248-4caa-9a0f-beeecf4dec62)

[303file.zip](https://github.com/DNPLab/DNPLab/files/12587624/303file.zip)

**Comment by thorstenmaly** [comment]
When I check the imported values, they seem to be correct. Maybe this is a plotting issue.

**Comment by thorstenmaly** [comment]
This was actually a bug in the SpecMan import function and it has been fixed.
Will be published with the next release
