### ISSUE TITLE
[Warning] 'product' is deprecated and will be removed in NumPy 2.0

### ISSUE THREAD

**Issue by ehuang94** [DNPLab/DNPLab#411]
The 'product' function will be removed in the future. In DNPLab, we use the h5py package for h5 file saving, and the package uses the 'product' function.

**Comment by tkeller12** [comment]
Let's update h5py and see if this is still an issue

**Comment by ehuang94** [comment]
The warning doesn't show up when using the latest h5py package 3.10.
