### ISSUE TITLE
Make DNPData objects compatible with pow operator

### ISSUE THREAD

**Issue by tkeller12** [DNPLab/DNPLab#467]

**Comment by Bkaribo** [comment]
does this work?

import dnplab as dnp
import numpy as np

a = dnp.DNPData(np.arange(100).reshape((10,10)),['t{0}'.format(k) for k in range(10)], [np.arange(10) for k in range(10)])
b = np.power(a,2)

print( np.all( np.isclose( b.values[1:,:]/a.values[1:,:], a.values[1:,:]) ) )
