### ISSUE TITLE
Installation via pip no longer works due to missing docs directory

### ISSUE THREAD

**Issue by ijday** [DNPLab/DNPLab#490]
PS C:\Users\dayi> pip install --upgrade dnplab
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: dnplab in c:\users\dayi\appdata\roaming\python\python311\site-packages (2.1.19)
Collecting dnplab
  Downloading dnplab-2.1.20.tar.gz (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.5/97.5 kB 793.2 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\dayi\AppData\Local\Temp\pip-install-b8bqs5tg\dnplab_9fde3116e5cc4ca89c1008910d6720f3\setup.py", line 11, in <module>
          with open("docs/requirements.txt", "r") as f:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: 'docs/requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by ijday** [comment]
Looks like the docs directory is not included in .tar.gz file on Pypi

**Comment by tkeller12** [comment]
This was resolved in the latest release
