### ISSUE TITLE
Add flag to load function to automatically sum up spectra

### ISSUE THREAD

**Issue by thorstenmaly** [DNPLab/DNPLab#516]
When averaging, we often save data in between. This typically results in a list of files that later all need to be added.

By adding a flag to the import function e.g. add_similar_data = True, we can do this automatically when importing the data. The default should be False. Only enable this, when the user sends a list of file names (there is already some behavior of the import function, that creates a 2D data object from a list of file names, but doesn't add identical dimensions).

Generate warning or error when dimensions are not the same for two files.

**Comment by ehuang94** [comment]
The sum function can be used as a single line. We will not address this issue.
