### ISSUE TITLE
Fourier transform function should work with default parameters for non-NMR data

### ISSUE THREAD

**Issue by tkeller12** [DNPLab/DNPLab#527]
File "d:\users\tkeller\repositories\dnplab\dnplab\processing\fft.py", line 93, in fourier_transform
    nmr_frequency = out.attrs["nmr_frequency"]
                    ~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'nmr_frequency'

**Comment by tkeller12** [comment]
fourier_transform function should give a warning if "nmr_frequency" not detected. Warning should indicated axis in Hz

**Comment by ehuang94** [comment]
This is solved.
