### ISSUE TITLE
Coords not correct when importing SpecMan data

### ISSUE THREAD

**Issue by thorstenmaly** [DNPLab/DNPLab#534]
The coords are not properly imported by the load function for SpecMan data when using autodetect_coords = True.

`
import dnplab as dnp

filename = "1925file.exp"
data = dnp.load(filename, autodetect_dims=True, autodetect_coords=True)
data = dnp.create_complex(data, "x")

data.coords["t2"] *= 0.8
data.coords["t"] *= 0.8

`

[1925file.zip](https://github.com/user-attachments/files/16429718/1925file.zip)

**Comment by ehuang94** [comment]
Which parameters is '0.8' from and is it an edge case?

**Comment by ehuang94** [comment]
This should be addressed in pull request #544

**Comment by tkeller12** [comment]
The transient axis must be handled differently from X, Y, Z axes.

**Comment by Bkaribo** [comment]
1925.file has in dnplab the coordinates

(4500,252)

array([0.000e+00, 1.000e+00, 2.000e+00, ..., 4.497e+03, 4.498e+03, 4.499e+03])
array([-1.000e-07, -8.400e-08, -6.800e-08, ...,  3.884e-06,  3.900e-06, 3.916e-06])

which seems to be correct with the .exp file:
idx = 1 step 1;p;PPL variable
transient = T,4500,500,a,b
t = -100 ns step 16 ns;p;PPL variable

tested with dnplab 2.1.30

**Comment by ehuang94** [comment]
This issue has been addressed.
