### ISSUE TITLE
Incorrect Import of 2nd dimension axes for 2D and Pseudo 2D data in JEOL Delta Data

### ISSUE THREAD

**Issue by rchaklashiya** [DNPLab/DNPLab#559]
**What happened**:
I am trying to process T1 data from JEOL Delta Software. However, my time interval axes are incorrect. The first and last point are correct, but instead of having the different time intervals in between, I am getting evenly spaced time intervals, which is not correct.

**What you expected to happen**:
I expect my time interval axes to be correct, as the user who took the data inputted.

**Minimal Complete Verifiable Example**:
Please see attached Word Document for all information about this issue. Unfortunately, it does not look like github is allowing me to attach the JEOL Delta .jdf file itself, so I emailed it to Thorsten and Tim. Please refer to that email for the data itself. [240924 DNPLab Issue with Importing Time Interval Axis for JEOL T1 data.docx](https://github.com/user-attachments/files/17119235/240924.DNPLab.Issue.with.Importing.Time.Interval.Axis.for.JEOL.T1.data.docx)

**Environment**:

I am using the latest version of DNPLab (2.1.30) on Windows 11.
Name: dnplab
Version: 2.1.30
Summary: DNPLab - Bringing the Power of Python to DNP-NMR Spectroscopy
Home-page: http://dnpLab.net
Author: DNPLab Team
Author-email:
License: MIT
Location: C:\Users\rajkc_n1emmcn\AppData\Local\Programs\Python\Python312\Lib\site-packages
Requires: h5py, matplotlib, numpy, scipy
Required-by:

**Comment by tkeller12** [comment]
This issue is now closed in the development branch.
