### ISSUE TITLE
Specific Fitting Functions for T1, T2 data needed

### ISSUE THREAD

**Issue by tkeller12** [DNPLab/DNPLab#563]
To the fitting module, we should add functions for fitting specific types of data.

Something like this should work:
`fit = dnp.fit_t1(data)`

**Comment by Bkaribo** [comment]
example implemented in branch issue_563

functions implemented:
"buildup_function", "general_biexp", "general_exp", "ksigma_smax", "logistic", "t1", "t2"

can be called with e.g. dnp.fit_general_exp(dnpdata,dim,initial_prm,**kwargs)

**Comment by Bkaribo** [comment]
see #569
