### ISSUE TITLE
Enable numpy universal functions on dnpdata

### ISSUE THREAD

**Issue by ylin00** [DNPLab/DNPLab#57]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I try to sum a dnpdata. Instead of getting the sum, it generates a TypeError.

``` python
>>> import numpy, dnplab
>>> numpy.sum(numpy.array(1))
1
>>> numpy.sum(dnplab.dnpData.dnpdata(numpy.array(1)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in sum
  File "/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2242, in sum
    initial=initial, where=where)
  File "/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 85, in _wrapreduction
    return reduction(axis=axis, out=out, **passkwargs)
TypeError: sum() got an unexpected keyword argument 'axis'
```

**Describe the solution you'd like** 

```python
assert numpy.sum(dnplab.dnpData.dnpdata(numpy.array(1))) == numpy.sum(numpy.array(1)) == numpy.sum(1) == 1
```
same for `numpy.cos, numpy.sin` etcs defined in [numpy ufuncs](https://numpy.org/doc/stable/reference/ufuncs.html)

**Describe alternatives you've considered**

by accessing the `.values` attribute
```python
assert numpy.sum(dnplab.dnpData.dnpdata(numpy.array(1)).values) == 1
```

**Additional context**
Add any other context about the feature request here.

**Comment by tkeller12** [comment]
I believe this issue is caused by the "sum" method in the dnpdata class (which is inherited from the nddata class). 
https://numpy.org/doc/stable/user/basics.subclassing.html
