### ISSUE TITLE
interacting with the saved h5 outside of dnplab is not intuitive

### ISSUE THREAD

**Issue by thcasey3** [DNPLab/DNPLab#6]
Handling the h5 that is saved using dnplab by using dnplab functions is simple and intuitive. However, using the h5 with h5py is not. For example, using dnplab this works and is simple:
```
h5in = dnplab.dnpImport.h5.loadh5("..pathtofile..")
ksigma = h5in["hydration_results"]["ksigma"]
```
However, using h5py.File() requires:
```
h5in = h5py.File("..pathtofile..", "r")
ksigma = ["hydration_results"]["attrs"].attrs["ksigma"]
```
The two layered ```["attrs"].attrs``` is not intuitive and will present a challenge to users integrating dnplab code into their own.

**Comment by ylin00** [comment]
@thcasey3 Could you write a snippet to generate the problematic `..pathtofile..` ? And does the following test case satisfy?

```
ksigma = 0

### code snippet to generate h5file
path_to_file = "path/to/h5file"


h5in = h5py.File(path_to_file, "r")
assert ksigma == h5in["hydration_results"]["ksigma"]
```

**Comment by thcasey3** [comment]
@ylin00 the example hydration_parameters.h5 in the hydrationGUI_results folder can be used to demonstrate this, use below code: 
```
import dnplab
import h5py

path_to_file = "../dnplab/data/topspin/hydrationGUI_Results/hydration_parameters.h5"
h5in = h5py.File(path_to_file, "r")

assert 25.682521583976747 == h5in["hydration_results"]["attrs"].attrs["ksigma"]
assert 25.682521583976747 == h5in["hydration_results"]["ksigma"]
```
looks like issue #50 is pointing this out as well

**Comment by tkeller12** [comment]
We should expect  that when someone saves the data in .h5 format, they will use the load function to import the data. It is not intended for people to interact with the h5 object directly with h5py. Also, it is possible to view the .h5 contents with HDFView which is freely available online.
