### ISSUE TITLE
[Feature Request]: Calculate DNP signal enhancement

### ISSUE THREAD

**Issue by thorstenmaly** [DNPLab/DNPLab#8]
- Calculate enhancements for a series of DNP build-up spectra
- Spectra should be stored as a 2D array
- By default the first spectrum is the off signal (no microwave power) but maybe we can add a flag so the user can specify which spectrum is used as the off spectrum
- Enhancement should be calculated either from the max of each spectrum or from and integrated region of the spectrum.
- Furthermore, it should be possible to calculate the enhancement for different regions of the spectrum (e.g. calculate enhancements for both peaks in toluene or crude oil separately)

**Comment by ylin00** [comment]
@thorstenmaly Does the following example satisfies?

```
x = [
    [0, 0, 0, 1, 0, 0, 0],
    [0, 0, 1, 1, 1, 0, 0],
    [0, 1, 1, 1, 1, 1, 0],
    [0, 1, 1, 2, 1, 1, 0]
]


y = calculate_enhancement(x, ref=0, method='integration', interval=(2, 5))

assert y == [
    1, 
    3, 
    5, 
    6
]


y = calculate_enhancement(x, ref=0, method='max')

assert y == [
    1, 
    1, 
    1, 
    2
]

```

**Comment by thcasey3** [comment]
added in recent pull request
