### ISSUE TITLE
[Feature Request]: Common constants

### ISSUE THREAD

**Issue by thorstenmaly** [DNPLab/DNPLab#93]
Add procedure to DNPTools to have access to most common constants.
A very good reference for constants is here: [http://physics.nist.gov/constants]

**Comment by thcasey3** [comment]
@thorstenmaly what do you mean by add it to tools? you mean the documentation? or do you have suggestions for changing the show_dnp_properties(), radical_properties(), and mrProperties.py that you added?

**Comment by thorstenmaly** [comment]
My plan is to have commonly used constants in the package. So you can for example say dnp.pi() to get pi. Right now I saw that you guys import numpy for it but there may be other constants that are missing.
This is not a high priority and we can get back to it later.
