### ISSUE TITLE
Unsolicited output

### ISSUE THREAD

**Issue by thorstenmaly** [DNPLab/DNPLab#94]
Take a look at the first example in the documentation. The different functions generate output that is not necessary.

**Comment by thcasey3** [comment]
@tkeller12 i'll let you squash this one since you know what is causing it, right?

**Comment by thorstenmaly** [comment]
I did see some changes to the code that were supposed to fix this issue. I think the amount of output is reduced but there is still some left over output that shouldn't be there.

**Comment by thorstenmaly** [comment]
THis is fixed in 1.0.4
