### ISSUE TITLE
Rename axis for EPR spectra automatically

### ISSUE THREAD

**Issue by thorstenmaly** [DNPLab/DNPLab#95]
By default, when a spectrum is loaded the x-axis is named "f2". This doesn't make much sense for EPR data and currently the user has to manually rename the x-axis to e.g. "B". Can we add a feature that automatically renames the axis to "B" when an EPR spectrum is imported?

**Comment by tkeller12** [comment]
By default the winepr import module names the "field" dimension "G" which indicates the units are in Gauss. I agree we should change this to something more appropriate. I would change this to "B0".
